import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import util from 'util';

export const dynamic = 'force-dynamic';

const execAsync = util.promisify(exec);

// In-memory registry of launched sub-apps
interface RunningApp {
  appId: string;
  name: string;
  port: number;
  pid?: number;
  startedAt: string;
  localPath: string;
}

const RUNNING_APPS = new Map<number, RunningApp>();

export async function GET() {
  const list = Array.from(RUNNING_APPS.values());
  return NextResponse.json({
    success: true,
    runningApps: list
  });
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { 
      appId, 
      appName, 
      localPath, 
      routerId, 
      baseUrl, 
      apiKey, 
      model,
      port = 3001,
      autoStart = false
    } = body;

    if (!localPath) {
      return NextResponse.json({ success: false, error: 'localPath is required' }, { status: 400 });
    }

    const rootDir = process.cwd();
    const targetDir = path.resolve(rootDir, localPath);

    if (!fs.existsSync(targetDir)) {
      return NextResponse.json({ 
        success: false, 
        error: `Directory not found: ${localPath}` 
      }, { status: 404 });
    }

    // 1. Generate or update .env in target app
    const envPath = path.join(targetDir, '.env');
    const existingEnv = fs.existsSync(envPath) ? fs.readFileSync(envPath, 'utf8') : '';

    const effectiveApiKey = apiKey || (
      routerId === 'lm-studio' ? 'lm-studio' :
      routerId === 'ollama' ? 'ollama' :
      routerId === 'nvidia-nim' ? (process.env.MY_MODEL_API_KEY || 'nvapi-configured') :
      routerId === 'gemini' ? (process.env.GEMINI_API_KEY || 'gemini-key') :
      'local-key'
    );

    const generatedEnvConfig = [
      `# Generated by Awesome Generative AI Apps Hub - Model Router`,
      `# Date: ${new Date().toISOString()}`,
      `# Active Model Router: ${routerId || 'custom'}`,
      `AI_PROVIDER="${routerId || 'lm-studio'}"`,
      `LM_STUDIO_URL="${baseUrl || 'http://127.0.0.1:1234/v1'}"`,
      `OPENAI_BASE_URL="${baseUrl || 'http://127.0.0.1:1234/v1'}"`,
      `OPENAI_API_BASE="${baseUrl || 'http://127.0.0.1:1234/v1'}"`,
      `OPENAI_API_KEY="${effectiveApiKey}"`,
      `AI_MODEL_NAME="${model || 'qwen2.5-coder-7b-instruct'}"`,
      `NEXT_PUBLIC_AI_MODEL="${model || 'qwen2.5-coder-7b-instruct'}"`,
      `MU_API_KEY="${process.env.MUAPI_API_KEY || effectiveApiKey}"`,
      `DATABASE_URL="file:./dev.db"`,
      `NEXTAUTH_SECRET="awesome_generative_ai_secret_${Date.now()}"`,
      `NEXTAUTH_URL="http://localhost:${port}"`,
      `PORT=${port}`,
      ``
    ].join('\n');

    // Write .env
    fs.writeFileSync(envPath, generatedEnvConfig, 'utf8');

    // 2. Prepare Command scripts
    const psCommand = `cd "${targetDir}"; npm run dev -- -p ${port}`;
    const cmdCommand = `cd /d "${targetDir}" && npm run dev -- -p ${port}`;

    let launched = false;
    let pid: number | undefined;

    if (autoStart) {
      try {
        // Use detached PowerShell process to avoid blocking
        const spawnCmd = `powershell -Command "Start-Process cmd.exe -ArgumentList '/c npm run dev -- -p ${port}' -WorkingDirectory '${targetDir}' -WindowStyle Hidden"`;
        const { stdout } = await execAsync(spawnCmd);
        launched = true;

        RUNNING_APPS.set(port, {
          appId: appId || localPath,
          name: appName || appId || 'AI App',
          port,
          startedAt: new Date().toISOString(),
          localPath
        });
      } catch (err: any) {
        console.error('Launch error:', err);
      }
    }

    return NextResponse.json({
      success: true,
      envPath,
      port,
      launched,
      commands: {
        powershell: psCommand,
        cmd: cmdCommand,
        npxPrisma: `cd "${targetDir}"; npx prisma db push`,
        npmInstall: `cd "${targetDir}"; npm install`
      },
      deploy: {
        vercelUrl: `https://vercel.com/new/git/external?repository-url=https://github.com/xennials-dev/awesome-generative-ai-apps&root-directory=${encodeURIComponent(localPath)}`,
        dockerRun: `docker run -p ${port}:${port} -e OPENAI_BASE_URL="${baseUrl}" -e OPENAI_API_KEY="${effectiveApiKey}" awesome-ai-app`
      }
    });

  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const port = Number(searchParams.get('port') || 3001);

    // Kill process on port using PowerShell
    await execAsync(`powershell -Command "$c = Get-NetTCPConnection -LocalPort ${port} -ErrorAction SilentlyContinue; if ($c) { Stop-Process -Id $c.OwningProcess -Force -ErrorAction SilentlyContinue }"`);
    RUNNING_APPS.delete(port);

    return NextResponse.json({ success: true, port, message: `Terminated process on port ${port}` });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
